### ISSUE TITLE
how to implement redux-saga

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#104]
hi, one question, how to implement redux saga, I try but always de result is wrong and always receive promises not fetch data

**Comment by joacub** [comment]
Is easy to implement the solution is yield for wait a promise. Can close this thanks

**Comment by bertho-zero** [comment]
Ok, thanks

**Comment by ilusharulkov** [comment]
Hello! Can you provide an example of implemeting saga with this boilerplate ?
