### ISSUE TITLE
EventEmitter memory leak detected. 11 exit listeners added

### ISSUE THREAD

**Issue by saisivaram94** [bertho-zero/react-redux-universal-hot-example#121]
I am getting this error (pic attached) when I run the example in dev mode. Doesn't seem to occur in production though. I looked up the error on StackOverflow but I am unable to solve the issue.

I am new to react and redux, and web dev in general. I am trying to make sense of this code to the best of my abilities, but I am having a hard time. I would be eternally grateful if someone could (briefly) walk me through it, if possible.

At any rate, thanks a lot for this boilerplate. It's wonderful. Advanced for a beginner like me I guess, but I am trying my best. :)

![issue](https://cloud.githubusercontent.com/assets/13402119/23460138/bb21f9de-fea9-11e6-87ee-be43efa4c78f.png)

**Comment by saisivaram94** [comment]
Can anyone please look into this? I have tried multiple solutions but none have worked for me. 
I tried doing **process.setMaxListeners(0)**, **Emitter.defaultMaxListeners = 0**, **npm install -g npm@next** like many people have suggested in various forums, but none of them haven't worked for me. :(

**Comment by arfianadam** [comment]
I've faced this problem several times and in several occasions. One thing I noticed is this would happen when I have both Gitkraken and this dev server running. It's another case with my other system. It would happen when I have both Sublime and this dev server running. I thought the reason was because I was running multiple process that requires listeners and my system can't handle it.

I don't know for sure, though. I also read many questions at SO and found no answers. No hurt in trying my solution above, though.

**Comment by bertho-zero** [comment]
It probably comes from there, if it can help you:

https://docs.feathersjs.com/v/auk/faq/readme.html#i-got-a-possible-eventemitter-memory-leak-detected-warning

**Comment by saisivaram94** [comment]
Hey, @arfianadam , I tried your suggestion, but it did not work for me. :(
I was able to figure out though that this issue happens whenever I use Chat and Chat with Feathers during my tests. So maybe it has got something to do with feathers. I will try @bertho-zero 's suggestion and see if it resolves the issue.

**Comment by arman-mukatov** [comment]
This may be due to the version of "piping@1.0.0-rc.4", see below..

[https://github.com/mdlawson/piping/issues/21](url)

**Comment by arfianadam** [comment]
Darn, I think I also got caught in this situation again and this time I can't find the solution. The leak appears everytime I run `npm run dev`.

https://github.com/mdlawson/piping/issues/21 tells (thanks, @arman-mukatov) that I should downgrade `piping` to `^0.3.0` and surprisingly it works! Sadly he said that this only happens on Ubuntu, and I am running Ubuntu. He alse mentioned that using `^0.3.0` will suffer from performance issues that are absent in `1.0.0-rc.4`. Well, I am waiting if anybody has come up with anything.
