### ISSUE TITLE
Async Auth for Router

### ISSUE THREAD

**Issue by agungsb** [bertho-zero/react-redux-universal-hot-example#14]
Hi, 

I'm starting to use this repo for my application. I need to do an async authentication to my API (I'm using an HTTP-only Cookie). Current onEnter handler is:

```
  const loadAuthIfNeeded = cb => {
    console.log(cb);
    if (!isAuthLoaded(store.getState())) {
      console.log('!isAuthLoaded');
      return store.dispatch(loadAuth()).then(() => cb());
    }
    console.log('isAuthLoaded');
    return cb();
  };

  const checkUser = (cond, replace, cb) => {
    const { auth: { user } } = store.getState();    
    if (!cond(user)) {
      console.log('we need to redirect');
      replace('/404');
    }
    cb();
  };

  const requireLogin = (nextState, replace, cb) => {
    const cond = user => !!user;
    loadAuthIfNeeded(() => checkUser(cond, replace, cb));
  };
```

For example, route that requires logged in is ```/login```.

Everything is fine everytime I navigate to that route from routes that don't require any authentication check (example, I start from ```/``` then I navigate to ```/login``` via anchor link). But if I directly access ```/login``` from URL address bar of the browser, the page is loading like forever. Page is not loaded. I think there is a problem with ```cb()```.

Any thoughts?

**Comment by VSuryaBhargava** [comment]
You may need an else condition in 

loadAuthIfNeeded

Since you are loading data asynchronously if it is not present you you need an else statement for the case if data is already loaded. 

Currently the cb will be called weather the data is loaded or not because of the return cb()  which is not in an else condition.
