### ISSUE TITLE
Yeoman generator is there

### ISSUE THREAD

**Issue by bertho-zero** [bertho-zero/react-redux-universal-hot-example#15]
The first version of yeoman generator is there, his npm package is available here: [generator-react-redux-universal](https://www.npmjs.com/package/generator-react-redux-universal)

First, install Yeoman and generator-react-redux-universal using npm (we assume you have pre-installed node.js).

```
npm install -g yo
npm install -g generator-react-redux-universal
```

```
> mkdir project && cd project
> yo react-redux-universal
     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │   react-redux-universal  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Project name project
? Description 
? Would you like an authentication? (uses passport) Yes
? Would you like oauth strategies? (Press <space> to select)Facebook
? Would you like a database? (optional) none (nedb if auth needed)
? Would you like a realtime? (useful for events, uses socket.io) Yes
? Would you like your application to be accessed offline? Yes
? Would you like examples? 
 ◉ Redux-form (widgets, survey)
 ◉ Simple chat socket
 ◉ Secure and persistent chat, even in socket
❯◉ Sample page (about us)
```

**Comment by evgenyboxer** [comment]
Great work!!! 💃

**Comment by bertho-zero** [comment]
Thank you, feel free to comment here if you see errors, omissions or bad linting.

**Comment by leopku** [comment]
Great work +1

**Comment by rizkiandrianto** [comment]
Takes time sooooo long to install with minimal features.. :sleepy:  

![image](https://cloud.githubusercontent.com/assets/2457820/20243764/b05e8286-a997-11e6-9f4e-a0bf0bd502a8.png)

**Comment by bertho-zero** [comment]
As you can see on the npm's warning, you need to update your version of npm and node.

Npm's progress bar may be responsible for up to 50% slow down. https://github.com/npm/npm/issues/11283
You can run `npm set progress=false`.
