### ISSUE TITLE
The usage of permissionsComponent

### ISSUE THREAD

**Issue by MHerszak** [bertho-zero/react-redux-universal-hot-example#170]
Hi,

I was under the impression I could use `permissionsComponent` like this: 
`<Route {...permissionsComponent([UserIsAuthenticated, UserIsAdmin])()}>`. But I am getting an Error: `onEnter is not a function`. Any idea what is happening here. I am going through your source code and do not see the problem.

Regards,

**Comment by bertho-zero** [comment]
Replace

```js
<Route {...permissionsComponent([UserIsAuthenticated, UserIsAdmin])()}>
```

by

```js
<Route {...permissionsComponent(UserIsAuthenticated, UserIsAdmin)()}>
```

**Comment by MHerszak** [comment]
Thanks! I got tricked by those spread operators :)
