### ISSUE TITLE
Would offline feature not work on localhost

### ISSUE THREAD

**Issue by simran66** [bertho-zero/react-redux-universal-hot-example#178]
I have cloned your project and running it on my localsystem without https. I see that network tab loads resource from service worker on your live website but no doing so on my local system. Is there a reason for that? I believed service workers should work on localhost without https but that does not look like it. I have attached a snapshot as well. 

All the resources are either loaded from memory cache or disk cache
![sw](https://cloud.githubusercontent.com/assets/4191009/24343595/e5e0d574-12e4-11e7-85c7-9a0947a1784b.png)

**Comment by bertho-zero** [comment]
I see there are 4 errors in the console, can you show them to me ?
Chances are that it will stop the service worker.
