### ISSUE TITLE
Redirect on refresh

### ISSUE THREAD

**Issue by MHerszak** [bertho-zero/react-redux-universal-hot-example#196]
Hi,

I got an issue since I updated a feathers package, I think. I am getting redirected to login every time I refresh the browser. I am not able to figure it out.

Redirect to login with following query based on origin: `http://localhost:3000/login?redirect=%2Fdashboard`

I believe I will be redirected when no token, or user is returned, correct? Is this redirect coming from feathers?

Any idea?

**Comment by bertho-zero** [comment]
It's linked to the issue #251, this is since you updated feathers-authentication-client, there is an error with superagent
