### ISSUE TITLE
watch-client Issue

### ISSUE THREAD

**Issue by VSuryaBhargava** [bertho-zero/react-redux-universal-hot-example#2]
When I run watch-client I get the below error

user@user-All-Series:/media/user/drive/workspace/react/react-redux-universal-hot-example$ npm run watch-client

> react-redux-universal-hot-example@0.9.0 watch-client /media/user/drive/workspace/react/react-redux-universal-hot-example
> better-npm-run watch-client

running better-npm-run in /media/user/drive/workspace/react/react-redux-universal-hot-example
Executing script: watch-client

to be executed: node webpack/webpack-dev-server.js 
/media/user/drive/workspace/react/react-redux-universal-hot-example/webpack/dev.config.js:10
const { installVendorDLL, createSourceLoader, createHappyPlugin } = require('./helpers');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/media/user/drive/workspace/react/react-redux-universal-hot-example/webpack/webpack-dev-server.js:5:21)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)

npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch-client"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-redux-universal-hot-example@0.9.0 watch-client: `better-npm-run watch-client`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-universal-hot-example@0.9.0 watch-client script 'better-npm-run watch-client'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-universal-hot-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run watch-client
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-universal-hot-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/user/drive/workspace/react/react-redux-universal-hot-example/npm-debug.log

I fixed it by changing the webpack/dev.config.js
changed
var { installVendorDLL, createSourceLoader, createHappyPlugin } = require('./helpers');
to 
var installVendorDLL = require('./helpers').installVendorDLL,
    createSourceLoader = require('./helpers').createSourceLoader,
    createHappyPlugin = require('./helpers').createHappyPlugin;

Is that the right thing to do? or should I do something else?

**Comment by bertho-zero** [comment]
This is probably related to the version of node, what is your version of node?

**Comment by bertho-zero** [comment]
It's the version node, I'm in 6.2, I change it immediately.
