### ISSUE TITLE
React SSR does not seem to be working

### ISSUE THREAD

**Issue by Sicria** [bertho-zero/react-redux-universal-hot-example#20]
If you run the build then start prod and load the page it works fine, but if you then disable JS and reload the SSR does not seem to work.

``global.__DISABLE_SSR__`` is set to false by default but there still seems to be issues with SSR.

**Comment by bertho-zero** [comment]
Try `MAJ + F5`, it's the service-worker.
You can also delete service-worker, a device without JavaScript can not have service-worker.

**Comment by Sicria** [comment]
Thank you, I'll try remove service-worker and see if that fixes it.
