### ISSUE TITLE
Migrate from React.PropTypes to prop-types

### ISSUE THREAD

**Issue by matteocng** [bertho-zero/react-redux-universal-hot-example#214]
> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

[Migrating from React.PropTypes ](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes)

**Comment by bertho-zero** [comment]
Closes with https://github.com/bertho-zero/react-redux-universal-hot-example/commit/08d6f1d9d6a12298e1e2f27ba488b45b57f33e26
