### ISSUE TITLE
Retaining trailing slashes in restApp & client

### ISSUE THREAD

**Issue by andrewsantarin** [bertho-zero/react-redux-universal-hot-example#25]
Hi.

Just looking at the code and I think the HTTP request architecture is great!

**Question**
The only thing I have difficulties working with is `restApp` ([/src/redux/modules/auth.js](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/redux/modules/auth.js), uses [feathers.js](https://docs.feathersjs.com)) removing the trailing slashes every time I make a request. 

For example, `restApp.service('/user/login/')` is requested as:
`http://api.HOST:PORT/user/login`
instead of
`http://api.HOST:PORT/user/login/`
The API I'm provided with needs the trailing slash to work.

Is there a setting in the codebase or a reliable documentation for feathers which allows me to stop the `restApp` from omitting the trailing slash? I've been looking everywhere in the feathers docs but I find nothing on this.

**Comment by bertho-zero** [comment]
It is not possible at the moment because of feathers-rest [feathers-rest/src/client/base.js#L11](https://github.com/feathersjs/feathers-rest/blob/master/src/client/base.js#L11)

**Comment by andrewsantarin** [comment]
Aww... that's a downer. Thanks anyway, @bertho-zero.

Just one last question for this topic, if you could reply, it would be great: 
Is there an example of your direct superagent suggestion I can find or is that exactly why `ApiClient` exists?

**Comment by bertho-zero** [comment]
Yes indeed, this is exactly why `ApiClient` exist, you can use it with RESTful methods as follows:

![RESTful methods](https://docs.feathersjs.com/img/services-restful-actions.jpg)

For more details you can see the [direct connection](https://docs.feathersjs.com/clients/vanilla-rest.html) page on feathers documentation.

**Comment by andrewsantarin** [comment]
Thanks, @bertho-zero.
