### ISSUE TITLE
User not authenticated anymore after refresh.

### ISSUE THREAD

**Issue by MHerszak** [bertho-zero/react-redux-universal-hot-example#251]
This just happened. I am login into the application and authenticate successfully. After that I hit refresh and the systems logs me out with a redirect link. When I log what happens this is what I get back. Any idea how to resolve this? The `feathers-jwt` cookie is still in place.
```
09:31:29 users::get (server) 65.3 ms - 1 pending - FAILED undefined No record found for id 'undefined'
09:31:29 authentication::create (socketio) 66.5 ms - 0 pending - FAILED after No record found for id 'undefined'
09:31:35 authentication::remove (server) 1.1 ms - 0 pending
09:31:36 users::get (server) 69.4 ms - 0 pending
```
Can you explain the exact order of execution for a loadUser? I still have the token saved but I am unable to retrieve the user hence the "logout". Thank you.

**Comment by bertho-zero** [comment]
Does it work in development or doing SHIFT + F5?

**Comment by bertho-zero** [comment]
Fixed in https://github.com/bertho-zero/react-redux-universal-hot-example/commit/2fbbc02f59f500c9bd148914b4a1c7a65f81ba21, I think we can do better than that with the latest versions of feathers authentication packages.

**Comment by MHerszak** [comment]
@bertho-zero sorry I didn't see the comment above. Thanks for fixing this.

**Comment by demiters** [comment]
So should I use that fix branch or is the current master good to use too?

**Comment by bertho-zero** [comment]
You can use master.
