### ISSUE TITLE
Recent Authentication Changes

### ISSUE THREAD

**Issue by sanjitsaluja** [bertho-zero/react-redux-universal-hot-example#267]
I'm having difficulty setting the `token` set on `ApiClient.js` reliably. Seems `setJwtToken` is only called during login. What the best way to have token be set from the redux store's auth token? Without this any authenticated APIs fail.

This is perhaps not the right fix at all but I tried to fix this in the auth `load` but this only works when the server renders the page.
```
-    promise: ({ client }) => client.get('/auth/load')
+    promise: ({ client, restApp, app }) => client.get('/auth/load')
+    .then(setToken({ client, restApp, app }))
```

Any ideas appreciated.

**Comment by sanjitsaluja** [comment]
I was able to work around this by setting the token up in `src/client.js` after the store is created

```
    client.setJwtToken(store.getState().auth.accessToken);
```

**Comment by bertho-zero** [comment]
It's fixed with https://github.com/bertho-zero/react-redux-universal-hot-example/commit/b87f05e31c8738acce9260756096b99dde2dedf5#diff-f88400307c935d06eaffe236ebaeb7f0R148
