### ISSUE TITLE
Load page by checking stored token instead of '/auth/load'

### ISSUE THREAD

**Issue by andrewsantarin** [bertho-zero/react-redux-universal-hot-example#27]
Hi @bertho-zero.

The API I work with only has methods for logging in, which means that it wholly depends on me having to set the tokens on the browser or whatever I can store on the server. In other words, I can't invoke a `promise: client => client.get('/auth/load')` from the API server. 

Is it possible to just invoke, let's say, `promise: client => client.get('/users/login')`, and store the logged in result somewhere so that it persists until the user has logged out?

**Comment by bertho-zero** [comment]
Hi,

After the connection the token is saved in the localStorage and a cookie is set, you can see it [here](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/redux/modules/auth.js#L120).

You can use `app.storage.getItem(''feathers-jwt')`
