### ISSUE TITLE
Updating react-router and react-router-redux to newest?

### ISSUE THREAD

**Issue by demiters** [bertho-zero/react-redux-universal-hot-example#273]
I know the migration is pretty complicated so I wonder if this is planned at all for this boilerplate?

**Comment by bertho-zero** [comment]
I would like but [redux-connect](https://github.com/makeomatic/redux-connect/) is not yet ready for this (https://github.com/makeomatic/redux-connect/issues/107#issuecomment-286562322), first it is necessary that all the modules are compatible with react-router@4.
