### ISSUE TITLE
Error upgrade webpack2 error with redux-persit

### ISSUE THREAD

**Issue by anhdn** [bertho-zero/react-redux-universal-hot-example#280]
Hello,
I'm trying to upgrade webpack 2 but having issue with redux-persit? And i dont know what the issue is? Can anyone help me?

![image](https://cloud.githubusercontent.com/assets/864385/26831124/781d54e2-4af5-11e7-9485-13c10f2937bf.png)

**Comment by arman-mukatov** [comment]
Hi,

Try changing the value of the parameter - devtool: "source-map" to "eval"

**Comment by anhdn** [comment]
thanks @arman-mukatov
