### ISSUE TITLE
@asyncConnect deferred: true not working as expected

### ISSUE THREAD

**Issue by Sicria** [bertho-zero/react-redux-universal-hot-example#285]
I'm not sure if I'm misunderstanding this or not but I think I remember this working a couple of months ago.

When you navigate from Home to Widgets no data is loaded, but when you reload the page it is.

> If you navigated here from another page, the data was fetched from the client after the route transition. This uses the decorator method @asyncConnect with the deferred: true flag.

But that does not seem to be the case since no data is loaded.

Is this a bug or am I just misunderstanding what's supposed to be happening.

**Comment by MHerszak** [comment]
Could this be related? https://github.com/Rezonans/redux-async-connect/issues/72
