### ISSUE TITLE
Problems with package-lock, "bootstrap-sass": "^3.3.7" and Heroku

### ISSUE THREAD

**Issue by MHerszak** [bertho-zero/react-redux-universal-hot-example#291]
I played around with package-lock and I was unable to build on Heroku. The problem seemed to occur due to a wrong version of bootstrap-sass. I changed the version to "bootstrap-sass": "^3.3.6", and deployed again, still unable to build. I deleted package-lock and all went well. I am not really sure what went wrong but I would recommend to not commit package-lock. I also don't know if this is a good advice. Any ideas?

**Comment by bertho-zero** [comment]
It is true that npm 5 is not yet very stable. Closed with https://github.com/bertho-zero/react-redux-universal-hot-example/commit/82c7bda21bd226f67c2a19f89f6492deb0772ae3
