### ISSUE TITLE
Migrating from erikras/react-redux-universal-hot-example

### ISSUE THREAD

**Issue by parth-choudhary** [bertho-zero/react-redux-universal-hot-example#296]
I have an existing project which I have built using erikas repo.
Any idea how can I migrate to this one?

I come from a python background so not sure how to proceed.

Thanks for help in advance :)

**Comment by bertho-zero** [comment]
Many dependencies having changed it is now complicated to migrate an existing project from Erikras repo to this one. You can manually copy the majority of your containers and components and modify your routes manually.
