### ISSUE TITLE
Syncing Redux Stores Across Browser Tabs

### ISSUE THREAD

**Issue by agungsb** [bertho-zero/react-redux-universal-hot-example#30]
Hi,

I would love to know if there's any plan to make the application able to sync the redux stores accross browser's tabs?

I've read [this article](https://medium.com/@Scarysize/syncing-redux-stores-across-browser-tabs-fff04f975423#.2za35ac6b) and see [this repo](https://github.com/rt2zz/redux-persist-crosstab), but none is working with this repo.

I'll be glad if anyone would help. Thanks.

**Comment by bertho-zero** [comment]
Have you managed to do what you want?

**Comment by bertho-zero** [comment]
https://github.com/rt2zz/redux-persist-crosstab seems to work by downgrading the redux-persist version to less than 5.

Without further details I could not help you.

Do not hesitate to reopen.
