### ISSUE TITLE
how to stream pdf file from api server

### ISSUE THREAD

**Issue by ducnvhn** [bertho-zero/react-redux-universal-hot-example#301]
hi.
I am using html-pdf to create pdf file from html but don't want to store resulted pdf file on server. so how do I stream the file directly to client. in other words: i want to be able to set header of res object. 
please help.

**Comment by MHerszak** [comment]
You can check this repo maybe it'll help: https://github.com/MHerszak/feathers-example-fileupload its an updated fork.
