### ISSUE TITLE
Huge production files

### ISSUE THREAD

**Issue by JoeGrasso** [bertho-zero/react-redux-universal-hot-example#302]
First, I truly want to **_thank you_** for carrying the torch for erikas. This is one of the best repos I have seen in years.

But unless I am doing something wrong, the main.js file is huge as is the stylesheet file. I tried to use common-chunks-plugin (webpack 3.3) and while it does break up the files, and the css files do work in smaller bundles, the scripts don't work, and I get a console error: "webpackJsonp is not defined".

Are you aware if I am doing something wrong, or, do you have any intentions soon to break up the script files into smaller packages as well as separating out the vendor batch from the app?

Thanks for your attention to this question.

**Comment by dongcai** [comment]
+1 Thank you for carrying the torch for erikas!!!
Same issue here. my main js is 1.5M, and main.css is 856K (which is not minified as well.)
The first load seems to be slow and see a couple seconds of white screen before rending. See my site here: https://shopecific.com/
I was using erikas's version and it seems to be faster. It's demo site loads very faster: https://react-redux.herokuapp.com/

**Comment by dongcai** [comment]
Comparing these two demo sites:
https://react-hot-example.herokuapp.com/ (@bertho) - use Chrome hard refresh, see 1 sec blank page
https://react-redux.herokuapp.com/ (@erikas) - use Chrome hard refresh, I don't see the blank issue.
Bertho's one is using "Service Worker". Could be that causing slowness? #48

**Comment by bertho-zero** [comment]
I have this on '/' on production:
![image](https://user-images.githubusercontent.com/8525267/32693521-afcd16da-c72c-11e7-9756-a721055e82c0.png)

The second blank is actually due to the service worker, because it does not wait for the server response.
On the other hand the service-worker helps me to load my page in 480ms and that of Erikras load in 1.70-1.80s.
