### ISSUE TITLE
How would you make a basename work on this project?

### ISSUE THREAD

**Issue by Richacinas** [bertho-zero/react-redux-universal-hot-example#305]
Hi there,

Thanks for the great work updating erikras boilerplate. This is awesome!

I wanted to know how you would make a basename work in this project. I tried and tried to createMemoryHistory passing it:

```
  const basename = '/whatever'
  const location = req.url.replace(basename, '')
  const history = createMemoryHistory({ entries: [location], basename })
```

However, it just doesn't match my routes and it hangs, because it matches my parent Component, but not any children.

Here my basic routes:

```
    <Route path="/" component={App}>
    
      <IndexRoute component={Login}/>

      <Route path='home/'>
        <IndexRoute component={Home}/>
      </Route>

      { /* Catch all route */ }
      <Route path="*" component={NotFound} status={404} />

    </Route>
```

So, it matches "/" and tries to render App, but no child is matched because my guess is that it will be looking for "whatever/" and it doesn't match any routes.

Any ideas about why this happens? 

thanks a lot!

**Comment by bertho-zero** [comment]
Sorry for the late response.

I advise you not to use basename nor to cut the location but prefix all your links by "/whatever", which allows you to still go outside the application.

Something like:
```jsx
<Route path="/whatever" component={App}>
  // ...
</Route>
```

**Comment by Richacinas** [comment]
I managed to set it up a few weeks ago.

These are the relevant versions I'm using:


"react": "^16.1.1",
"react-router": "3.0.4"

And this is the relevant piece of code:

**server.js**

```
import { syncHistoryWithStore } from 'react-router-redux';
import createMemoryHistory from 'react-router/lib/createMemoryHistory';
import config from './myProjectConfig';

const basename = '/' + config.projectName;
const location = req.url.replace(basename, '')
const memoryHistory = createMemoryHistory({ entries: [location], basename })

const store = createStore(memoryHistory, { language: {lang: req.lang, nextLang: req.nextLang }});
const history = syncHistoryWithStore(memoryHistory, store);
...
```


**client.js**

```
import { createHistory } from 'history';
import { Router, useRouterHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import config from './myProjectConfig';

const browserHistory = useRouterHistory(createHistory)({
  basename: '/' + config.projectName
})

const store = createStore(browserHistory, window.__data);
const history = syncHistoryWithStore(browserHistory, store);
...
```

Please note that you don't need the history package installed, it is a react-router dependency and so it comes with it. You can just import it.

Cheers!
