### ISSUE TITLE
How to access assets on the server side?

### ISSUE THREAD

**Issue by rohit563** [bertho-zero/react-redux-universal-hot-example#311]
I'm using feathersjs to create a pdf service that generates a pdf. I'm using pdfmake and so far I have not been able to get it to work because it needs access to some .ttf (font) files. I've downloaded the font files but I'm not entirely sure where to put them so the server can have access to them. 

I've been trying to access them like so:

``` javascript
var fonts = {
        Roboto: {
            normal: './fonts/Roboto-Regular.ttf',
            bold: './fonts/Roboto-Medium.ttf',
            italics: './fonts/Roboto-Italic.ttf',
            bolditalics: './fonts/Roboto-Italic.ttf'
        }
    };
```

I've also tried using the ` require ` method and that did not work and I keep getting the following error: 
    `Error: ENOENT: no such file or directory, open './fonts/Roboto-Regular.ttf'`

My question is where do I put these files and how do I access them on the server side? Any help would be greatly appreciated. Thank you!

**Comment by maximelkin** [comment]
@rohit563 
Maybe problem in relative path?
For example, you call pdfmaker in module
/helpers/pdf-maker.js
pdfmaker search your fonts in /helpers/fonts/

**Comment by rohit563** [comment]
Thanks for replying! I've moved to font files to inside api/fonts/
So I've now done this: 

```
    const rbotoReg = require('./fonts/Roboto-Regular.ttf');
    const rbotoBold = require('./fonts/Roboto-Medium.ttf');
    const rbotoItal = require('./fonts/Roboto-Italic.ttf');
    const rbotoBI = require('./fonts/Roboto-Italic.ttf');

    var fonts = {
        Roboto: {
            normal: rbotoReg,
            bold: rbotoBold,
            italics: rbotoItal,
            bolditalics: rbotoBI
        }
    };
```
Now I'm getting this error: 
`SyntaxError: /Users/rohit/Desktop/react-redux-universal-hot-example-master/api/fonts/Roboto-Regular.ttf: Unexpected character '`

I think that has something to do with the webpack-isomorphic-tools config but I'm not entirely sure.

**Comment by maximelkin** [comment]
@rohit563 
1) Use .. in path to go in upper directories
2) just give it path like in example
https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js

**Comment by rohit563** [comment]
Lol. I feel so dumb. Thank you so much! That worked! I took the `require` method out and used `path.join()` and it worked perfectly. Thank you!
