### ISSUE TITLE
Node 8 and async/await?

### ISSUE THREAD

**Issue by demiters** [bertho-zero/react-redux-universal-hot-example#315]
Any plans to upgrade for that?

**Comment by MHerszak** [comment]
@demiters this is my setup in package.json
```
"engines": {
    "node": "8.1.4",
    "npm": "5.2.0"
  }
```
You can start to use async and await and you should have no issues.

**Comment by bertho-zero** [comment]
Closed with https://github.com/bertho-zero/react-redux-universal-hot-example/pull/330
