### ISSUE TITLE
asset not found:./src/containers/App/App.scss

### ISSUE THREAD

**Issue by xiaodu527** [bertho-zero/react-redux-universal-hot-example#33]
Hello? Could anyone help me?

I'm using windows10 , after cloning this repo and run "npm install " & "npm run dev", the first time, it throws a lots of error "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style",

Ctrl+C and "npm run dev" again, it throws error as following:

[1] [webpack-isomorphic-tools] [error] asset not found: ./src/containers/App/App.scss
[1] MOUNT ERROR:   TypeError: Cannot read property 'app' of undefined

**Comment by anhdn** [comment]
@xiaodu527  you try to empty file webpack-assert.json then 'npm run dev' again.

**Comment by bertho-zero** [comment]
You can reopen the issue if the problem persists
