### ISSUE TITLE
deferred: __SERVER__

### ISSUE THREAD

**Issue by pkumar01** [bertho-zero/react-redux-universal-hot-example#339]
Hi,

I am new to react world, was just going through this fork and got confused by "deferred: __SERVER__ " could someone please guide me on what "asyncConnect" does with deferred: __SERVER__. Because i checked many other files does not have this flag assigned in asyncConnect.

**Comment by bertho-zero** [comment]
> If you hit refresh on your browser, the data loading will take place on the server before the page is returned. If you navigated here from another page, the data was fetched from the client after the route transition. This uses the decorator method `@asyncConnect` with the `deferred: __SERVER__` flag. To block a route transition until some data is loaded, remove the `deferred: __SERVER__` flag. To always render before loading data, even on the server, use `componentDidMount`.

**Comment by pkumar01** [comment]
THanks for clarification
