### ISSUE TITLE
Getting error messages when will login using facebook

### ISSUE THREAD

**Issue by cyberid41** [bertho-zero/react-redux-universal-hot-example#342]
I get error messages when will login using facebook 

```
{"name":"GeneralError","message":"Failed to fetch user profile","code":500,"className":"general-error","data":{},"errors":{}}
```

the url is
`http://localhost:3000/api/authentication`

UPDATE:

I try to catch the error message like here on `modules/redux/auth.js`
```
const response = await restApp.authenticate({
          ...data,
          strategy,
          socketId
        }).catch(error => { console.log(error); });
```
and getting error message:

`Uncaught (in promise) TypeError: Cannot read property 'accessToken' of undefined auth.js:113`

**Comment by bertho-zero** [comment]
The uncaught error comes from the fact that you cancel the error with the .catch, which returns undefined.
You can avoid this behavior and keep the error like this:
```js
authenticate( /* ... */ ).catch(error => {
  console.log(error);
  throw error;
});
```

For the 'Failed to fetch user profile' error, are you sure of your account credentials? and did you configure the configuration in the [config.js](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/api/config.js) file?

**Comment by cyberid41** [comment]
Thank you for your response @bertho-zero , I tried it and it worked
