### ISSUE TITLE
Login page seems to be broken on fresh install

### ISSUE THREAD

**Issue by squidis** [bertho-zero/react-redux-universal-hot-example#348]
Hi, 

When running the app locally in dev mode, if I go to the login page and submit a valid local login the dev tools display the following error.

>  API ERROR:   TypeError: strategies.includes is not a function
>  - authenticate.js:77 
>     [react-redux-universal-hot-example]/[feathers-authentication]/lib/passport/authenticate.js:77:25
>- authenticate.js:38 
>     [react-redux-universal-hot-example]/[feathers-authentication]/lib/passport/a    uthenticate.js:38:14
> - authenticate.js:80 Object.<anonymous>
>     [react-redux-universal-hot-example]/[feathers-authentication]/lib/hooks/auth    enticate.js:80:55
>  - node.js:368 process._tickCallback
>     node.js:368:9
>POST /authentication 500 72.051 ms - 134

The error "strategies.includes is not a function" is also displayed above the login button. The rest of the app works correctly. I've tried to fix the error but I'm fairly new to your project and feathers/passport. Is this a known issue or am I maybe missing an install step?

Thanks for your continuing work on this project.

**Comment by bertho-zero** [comment]
Your version of node is too old, you can try to update it?

**Comment by squidis** [comment]
Thanks alot, that fixed it. Apologies for late reply.
