### ISSUE TITLE
Wait for data load before server side rendering

### ISSUE THREAD

**Issue by mauricioklein** [bertho-zero/react-redux-universal-hot-example#35]
Hello!

I would appreciate some help with this situation:

I'm using asyncConnect to pre-load some data from API before performing the server side rendering.
But now, I need to load another data when the first one has finished.

For example:
On asyncConnect I fetch all the users.
After all the users have been loaded, I need to fetch their subscriptions.

How can I handle a synchronous call on asyncConnect?

Thanks!

**Comment by mauricioklein** [comment]
@bertho-zero Do you have an idea how to do this?
Your opinion would be a great help :+1: 
Thanks!

**Comment by bertho-zero** [comment]
Hi,

For synchronous call you can use `connect` from react-redux, or add a `.then` after the dispatch, dispatch returns the promise of the action.

**Comment by mauricioklein** [comment]
Thanks, but I think that just the connect is not enough.

I've tried to put the following line on my `componentWillMount` method:

```js
Promise.resolve(dispatch(myAction()))
```

However, the whole tree is rendered on server side before the `myAction` is fulfilled and persisted on Redux store.

What I need is to block the tree rendering until this action is fulfilled.

Thanks!

**Comment by bertho-zero** [comment]
You can do:

```js
@asyncConnect([{
  promise: ({ store: { dispatch, getState } }) => {
    const promises = [];

    if (!isAuthLoaded(getState())) {
      promises.push(dispatch(loadAuth())
        .then(dispatch(YOUR_ACTION)));
    }

    return Promise.all(promises);
  }
}])
```
