### ISSUE TITLE
app.get() does not work on production

### ISSUE THREAD

**Issue by dongcai** [bertho-zero/react-redux-universal-hot-example#350]
I know this is weird. 
To reproduce, you may add the following code in src/server.js:
`app.get('/', (req, res) => {
  res.send('hello world');
});`
It works as expected on dev (npm run dev), but doesn't work on production (npm run build & npm run start) 
Looks like app.get() is just got ignored after build.

Assume the latest code is on herokuapp.com, you can see the following url returns '404 not found'.
https://react-hot-example.herokuapp.com/maifest.json
And it's using app.get() as well.
`app.get('/manifest.json', (req, res) => res.sendFile(path.join(__dirname, '..', 'static', 'manifest.json')));`

**Comment by bertho-zero** [comment]
This is fixed with react-router v4 pull request.

**Comment by dongcai** [comment]
Thanks @bertho-zero!
I just checked out the latest master, and saw the change of "react-router 4 & react-loadable & redial". Looks like this is a huge change.
However, since I am building application on the top of "react-redux-universal-hot-example", I have to pretty much re-write everything components. Pretty painful. Is this what we should expected?

**Comment by bertho-zero** [comment]
That's a big change, but I think it's pretty stable now and there will not be such a big change anytime soon.
