### ISSUE TITLE
Remove Feathers API dependencies and use already built Backend API

### ISSUE THREAD

**Issue by junaidcs** [bertho-zero/react-redux-universal-hot-example#353]
Hi guys, really great work with this boilerplate, i've one question, what's the way to completely remove feathers backend api,i don't want to use feathers api and its dependencies, i'd like to use the api we've already built.

Please explain the way. Thanks

**Comment by bertho-zero** [comment]
You can start by removing all app, restApp, & auth usage on:

- `src/app.js`
-` src/client.js`
- `src/server.js`
- `src/redux/modules/auth.js`
- `src/redux/modules/chat.js`
- `src/containers/ChatFeathers/ChatFeathers.js`

You can also remove/modify all usages of the redux authentication on:

- `src/containers/App/App.js`
- `src/containers/Login/Login.js`
- `src/containers/LoginSuccess/LoginSuccess.js`
- `src/containers/Register/Register.js`

And you can remove/modify redux-auth-wrapper from src/routes.js.
I may have forgotten something but it seems like a good starting point.

**Comment by junaidcs** [comment]
Thanks, i've removed it from all the places if was being used in.
