### ISSUE TITLE
Missing immutable

### ISSUE THREAD

**Issue by dongcai** [bertho-zero/react-redux-universal-hot-example#356]
I am doing the fresh installation from the latest Master. I got the following warnings. I understand that most of them are fine because we have higher version of dependencies installed. But how about "immutable"? I remember in the previous commits, I added 'immutable' by myself as well since I thought it's needed for multireducer. Is "immutable" missing accidenlty in the package.json?

```
npm WARN less-loader@4.0.5 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN multireducer@3.1.0 requires a peer of immutable@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN redux-devtools-dock-monitor@1.1.2 requires a peer of react@^0.14.9 || ^15.3.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by bertho-zero** [comment]
I have created this pull request for fix this: https://github.com/erikras/multireducer/pull/125

Immutable is an optionnal dependency, not really a peerDependencies.

**Comment by dongcai** [comment]
Good to know. Thanks!

**Comment by bertho-zero** [comment]
The pull request has been merged and the package version bumped, there is more than waiting for it to be published on NPM.
