### ISSUE TITLE
What's about nested routes?!

### ISSUE THREAD

**Issue by ducnvhn** [bertho-zero/react-redux-universal-hot-example#357]
Hi @bertho-zero .
I've been follow this repo for pretty long time and observed many changes recently. having hard time figuring out the new React-router-4. In your routes.js file I cannot find any nested routes although react-router-config.  
I want to have a child routes for home like this 
````
const routes = [
  {
    component: App,
    routes: [
      {
        path: '/',
        exact: true,
        component: Home,
        routes: [
          { path: "/pageone", component: PageOne, exact: true},
          { path: "/pagetwo", component: PageTwo, exact: true },
        ]
      },
....
// rest of the router
]
````
And in Home.js container
````
import { renderRoutes } from 'react-router-config';
....
render() {
  const { route } = this.props;
  return (
    <div>
      <h1>Home</h1>
      <ul>
          <li><Link to="/pageone">child Page One</Link>
          <li><Link to="/pagetwo">child Page Two</Link>
      </ul>
      {renderRoutes(route.routes)}
    </div>
  );
}
````
### Expected Behavior 
I want to be able to navigate to page one and page two. and if not match -> go to NOT FOUND. Other routes in your setup must work as normal.
### Actual behavior
I can navigate to page one and page 2 (remove the ````exact: true```` from the routes to Home above). But if the route is not match, the home page will be display not the NOTFOUND page.  

Can you guide me please?

**Comment by bertho-zero** [comment]
I do not know how to adjust the exact option, I let you test the different possibilities, in my opinion you can remove the `exact: true`.

I think that [Redirect](https://reacttraining.com/react-router/web/api/Redirect) can be useful to you, something like:
```jsx
import { Redirect } from 'react-router';

const routes = [
  {
    component: App,
    routes: [
      {
        path: '/',
        component: Home,
        routes: [
          { path: "/pageone", component: PageOne },
          { path: "/pagetwo", component: PageTwo },
          { component: () => <Redirect to="/404" /> }
        ]
      },
      // ....
      // rest of the router
    ]
  }
];
```

###### (I did not try)

**Comment by ducnvhn** [comment]
Thanks for your advise. I will give it a try.
