### ISSUE TITLE
Param with react-router 4 and redial

### ISSUE THREAD

**Issue by tention** [bertho-zero/react-redux-universal-hot-example#358]
Hi @bertho-zero,

Having a hard time figuring out how the new react-router v4 and redial works to get param from URL. 

React route: `{ path: '/post/:id', component: Post }`

Following are the codes that works previously with redux-connect to get the id from a URL.

```
@asyncConnect([{
  promise: ({ store: { dispatch, getState }, params: { id }, }) => {
    const state = getState();

    if (state.online) {
      return dispatch(action.load(id));
    }
  }
}])
```

After upgrading to react-router v4 and redial, I changed the code to the following, but keep getting `Error on routes reload: TypeError: Cannot read property 'id' of undefined`.

```
@provideHooks({
  fetch: async ({ store: { dispatch, getState, inject }, params: { id } }) => {
    inject({ portfolios: reducer });

    const state = getState();

    if (state.online) {
      return dispatch(action.load(id)).catch(() => null);
    }
  }
})
```
Any advise or guidance would be greatly appreciated! Thanks

**Comment by bertho-zero** [comment]
I forgot to pass `match, location, history` to redial triggers (https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/components/ReduxAsyncConnect/ReduxAsyncConnect.js#L31)

I do it as soon as I have a little time. Thanks

**Comment by bertho-zero** [comment]
It's fixed in https://github.com/bertho-zero/react-redux-universal-hot-example/commit/38c1a225125640a35f91f3003114710986cd70c2

**Comment by tention** [comment]
Thanks!
