### ISSUE TITLE
Callbacks error on server side rendering

### ISSUE THREAD

**Issue by mauricioklein** [bertho-zero/react-redux-universal-hot-example#36]
Hello!

I'm facing a strange behavior:
My server side rendering is being made correctly but, for some reason, the callback is not being triggered.

Everytime I click on my link, instead calling the callback method passed as props, it's triggering a `@@redux/INIT` and `@@router/LOCATION_CHANGE`. But my link is something like:

```javascript
<a href="#" onClick={() => this.props.myCallback(argument)}></a>
```

This works well when SSR is disabled.

Also, all the promises defined in @asyncConnect are re-run when I click on the link above.

Any idea why is this happening?

Thanks!

**Comment by mauricioklein** [comment]
@bertho-zero Do you have an idea why is this happening? 
I've read the async connect documentation but got no clue about this.
Thanks!

**Comment by bertho-zero** [comment]
Hi,

If you want to use a link with an onClick you must first make an e.preventDefault.

This behavior is never performed on the server side, the link can not be clicked (except manually) on the server side.

**Comment by mauricioklein** [comment]
Prevent default worked as expected.
Thanks @bertho-zero :+1:
