### ISSUE TITLE
send cookies for client side ajax request

### ISSUE THREAD

**Issue by Swapnilchavan18** [bertho-zero/react-redux-universal-hot-example#364]
I observed that it does not send cookies for client side request , also req obj comes undefined in apiclient for client side ajax request.

**Comment by bertho-zero** [comment]
What is your issue ?

The auth cookie, only used, is defined here:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/903c2ca1cff433d830b68964bc941330ea3d2959/src/redux/modules/auth.js#L112-L119

**Comment by Swapnilchavan18** [comment]
Hey, thanks for nice repository, I was doing wrong, checking on subdomain.
