### ISSUE TITLE
Is there any way to modify request headers based on some conditions through apiclient? 

### ISSUE THREAD

**Issue by Swapnilchavan18** [bertho-zero/react-redux-universal-hot-example#367]
This is question, not an issue

**Comment by bertho-zero** [comment]
Yes with [axios](https://github.com/axios/axios), `apiClient` is just an instance of axios:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/903c2ca1cff433d830b68964bc941330ea3d2959/src/helpers/apiClient.js#L4-L7

If you need, you can replicate the changes on `restApp` (https://github.com/bertho-zero/react-redux-universal-hot-example/blob/903c2ca1cff433d830b68964bc941330ea3d2959/src/app.js#L24) like this:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/903c2ca1cff433d830b68964bc941330ea3d2959/src/app.js#L28-L33
