### ISSUE TITLE
can react-loadable show loader like github or medium.com, while loading chunks?

### ISSUE THREAD

**Issue by Swapnilchavan18** [bertho-zero/react-redux-universal-hot-example#369]
Hi, 
Let me know your suggestions on this, currently it hides previous page, but it will be really cool to show loader and show previous page until its being loaded?

**Comment by bertho-zero** [comment]
Done with https://github.com/bertho-zero/react-redux-universal-hot-example/commit/a5d8bda2492af8450f10c2f3bf16f49e513be72b
