### ISSUE TITLE
Upgrade feathersjs to v3

### ISSUE THREAD

**Issue by abeMedia** [bertho-zero/react-redux-universal-hot-example#370]
Feathers v3 was released at the beginning of November. Any plans to upgrade this boilerplate to the latest version?

**Comment by ducnvhn** [comment]
waiting for this too!

**Comment by bertho-zero** [comment]
#meToo

**Comment by bertho-zero** [comment]
#MeToo

**Comment by bertho-zero** [comment]
More seriously, I do it as soon as I have a little time.
It should not be very complicated and if someone wants to submit a pull-request, do not hesitate.

I also thought to replace the "simple" API (widgets and surveys) by feathers services to keep only one system, what do you think?

**Comment by ducnvhn** [comment]
OK. So I have migrated successfully to feathersjs v3. Some note for @abeMedia if you want to try your self. Just follow [Migrating guide](https://buzzard.docs.feathersjs.com/migrating.html) to replace according packages and you are good to go. 
you need to change the code in 'src/app.js' and 'api/api.js':
for `src/app.js` file
```
// import feathers from 'feathers/client';
import feathers from '@feathersjs/feathers';
// import hooks from 'feathers-hooks';
// import rest from 'feathers-rest/client';
import rest from '@feathersjs/rest-client';
// import socketio from 'feathers-socketio/client';
import socketio from '@feathersjs/socketio-client';
// import authentication from 'feathers-authentication-client';
import authentication from '@feathersjs/authentication-client';
...
const configureApp = transport =>
  feathers()
    .configure(transport)
    // .configure(hooks()) // we dont need this one since hooks is included
    .configure(authentication({ storage }));
```
for `api/api.js` : 
```
import feathers from '@feathersjs/feathers';
import express from '@feathersjs/express';
// import hooks from 'feathers-hooks';
// import rest from 'feathers-rest';
import rest from '@feathersjs/express/rest';
// import socketio from 'feathers-socketio';
import socketio from '@feathersjs/socketio';
.
.
.
// const app = feathers();
const app = express(feathers());
```
@bertho-zero  please correct me if I was wrong or missing some other places. 

Thank you.
