### ISSUE TITLE
Adding bootstrap tabs

### ISSUE THREAD

**Issue by junaidcs** [bertho-zero/react-redux-universal-hot-example#373]
Hi, 
I'm using bootstrap 4 beta in this boilerplate and updated `.bootstraprc` file accordingly.
Under `scripts` updated `tab` to true 
```
"tab": true,
```
And in webpack `dev.config.js` i've added below code in `plugins` array
```
new webpack.ProvidePlugin({
      $: "jquery", // Used for Bootstrap JavaScript components
      jQuery: "jquery", // Used for Bootstrap JavaScript components
      Util: "exports-loader?Util!bootstrap/js/dist/util",
    }),
```

And now tabs are working. 
Just want to make sure if  this is the right way to do or there is another workaround without changing the webpack config file?

Thanks

**Comment by bertho-zero** [comment]
I advise you to use react-bootstrap for this: https://react-bootstrap.github.io/components/tabs/
