### ISSUE TITLE
How to use feathers channel with this boilerplate?

### ISSUE THREAD

**Issue by ducnvhn** [bertho-zero/react-redux-universal-hot-example#379]
hi @bertho-zero . 
I wanted to build a real-time web app that emit event to specific user by joining user to a room with the name is the _id of the user. With the current setup, I cannot do it since the user authentication information is not available in the socket object. Feathers channel is seems to be a good choice for my purpose but it is not setup in this boilerplate [This note on feathers channell](https://docs.feathersjs.com/api/channels.html) said that the channel is not available. could you please suggest a way to : 

1. join a user into a specific room with _id is the name of the room. 
2. using feathers channel 

Thank you very much.

**Comment by bertho-zero** [comment]
I need to update feathers to version 3.

**Comment by ducnvhn** [comment]
do you have any plan on this?
