### ISSUE TITLE
About database NeDB

### ISSUE THREAD

**Issue by iamnumberten** [bertho-zero/react-redux-universal-hot-example#386]
I found that you are using NeDB. I am  having difficulty understanding NeDB in this project. For Example: In MongoDB , after user registration,the database is automatically saved and  we can open robomongo and see them . How NeDB works? @bertho-zero

**Comment by tention** [comment]
Check the messages.nedb file created for Feathers Chat.

**Comment by iamnumberten** [comment]
I couldn't find it. Can you send me link. Another question- How can i view saved data (like there is robomongo for mongodb to see database).

**Comment by synchu** [comment]
.nedb is file-based and it is a plain text file. users.ndb is in api/services/users/users.nedb

**Comment by Shuyinsama** [comment]
I get that this is an example but how "safe" is this in a production environment?

neDB is not being maintained anymore on a feature level, there will be the occasional bug fix though. I like the idea of nedb in an example app. But in terms of adaptability how easy would it be to completely switch out nedb for mongodb?

Seeing as neDB is like the SQLite of MongoDB, I am guessing this is doable?
