### ISSUE TITLE
Integration with redux-saga

### ISSUE THREAD

**Issue by ilusharulkov** [bertho-zero/react-redux-universal-hot-example#388]
Hello! Thank you for your repository. It is great job!
I have idea to integrate redux-saga with this repository. It is awesome lib to asynchronous data fetching and manipulation.
I can send merge request to this repository with saga integration. Is it interesting?

**Comment by ilusharulkov** [comment]
ping )

**Comment by bertho-zero** [comment]
I have never used redux-saga but I am curious to see that.

Your pull request is welcome!

**Comment by bertho-zero** [comment]
I think that the choice of the state management library must be made by the developer, having only a few simple actions in the boilerplate there is no point in putting it automatically in the repo. Moreover, it's easy to implement.

If you make a pull request it will always serve as an example.
