### ISSUE TITLE
Client-Side Feathers

### ISSUE THREAD

**Issue by Sicria** [bertho-zero/react-redux-universal-hot-example#389]
Due to the recent upgrade to Feathers v3 this example no longer works in IE as feathers no longer transpiles packages other than ``@feathers/client``.

I believe this line should be converted to ``@feathers/client``. 
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/app.js#L1

I think the same goes for the other packages but I'm not too sure.

From my tests it builds the bundle with code which will work on newer browsers but no older ones like IE.

**Comment by bertho-zero** [comment]
To do: https://docs.feathersjs.com/api/client.html#webpack
