### ISSUE TITLE
the cookie is not remove

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#398]
need implement after logout remove the cookie my solutions is this 

```js
export function logout() {
  return {
    types: [LOGOUT, LOGOUT_SUCCESS, LOGOUT_FAIL],
    promise: async ({ client, app, restApp }) => {
      await app.logout();
      setToken({ client, app, restApp })({ accessToken: null });
      cookie.set('feathers-jwt', '');
    }
  };
}
```

if not implement this the session not is erase any time only sometimes.

**Comment by joacub** [comment]
sorry bertho but we have a same error when teh ssion is expire in the api but not in the client, so what you mean ?

**Comment by bertho-zero** [comment]
I think we have to wait for v3 of Feathers authentication.

**Comment by joacub** [comment]
Yeah I see this version and the features are very useful for more security and control, when is the release date ?

**Comment by bertho-zero** [comment]
It's been a while since I did not update this project, I do not find much time for this one. I would have to find some.
