### ISSUE TITLE
When opening /widgets directly server side render is discarded apparently

### ISSUE THREAD

**Issue by sdkitono** [bertho-zero/react-redux-universal-hot-example#399]
Warning: Expected server HTML to contain a matching <div> in <div>.
printWarning @ warning.js:33
warning @ warning.js:57
warnForInsertedHydratedElement$1 @ react-dom.development.js:14483
didNotFindHydratableContainerInstance @ react-dom.development.js:15149
insertNonHydratedInstance @ react-dom.development.js:9490
tryToClaimNextHydratableInstance @ react-dom.development.js:9558
updateHostComponent @ react-dom.development.js:7954
beginWork @ react-dom.development.js:8229
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
hydrate @ react-dom.development.js:15287
_callee$ @ client.js:82
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
hydrate @ client.js:50
_callee3$ @ client.js:98
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ client.js:50
(anonymous) @ main-5d58b6a2d88742de1490.js:18459
__webpack_require__ @ bootstrap 5d58b6a2d88742de1490:707
fn @ bootstrap 5d58b6a2d88742de1490:112
options.path @ main-5d58b6a2d88742de1490.js:12315
__webpack_require__ @ bootstrap 5d58b6a2d88742de1490:707
module.exports @ bootstrap 5d58b6a2d88742de1490:805
(anonymous) @ bootstrap 5d58b6a2d88742de1490:805

client.js:113 Server-side React render was discarded.
Make sure that your initial render does not contain any client-side code.
_callee3$ @ client.js:113
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise.then (async)
step @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
F @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ client.js:50
(anonymous) @ main-5d58b6a2d88742de1490.js:18459
__webpack_require__ @ bootstrap 5d58b6a2d88742de1490:707
fn @ bootstrap 5d58b6a2d88742de1490:112
options.path @ main-5d58b6a2d88742de1490.js:12315
__webpack_require__ @ bootstrap 5d58b6a2d88742de1490:707
module.exports @ bootstrap 5d58b6a2d88742de1490:805
(anonymous) @ bootstrap 5d58b6a2d88742de1490:805

**Comment by bertho-zero** [comment]
It's due to the deferred hook:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/98a9386aca0998f4906aaec8a40174194735fcfe/src/containers/Widgets/Widgets.js#L11-L19
