### ISSUE TITLE
Update to React 16.3 >=

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#405]
Is interesant the new api context of react 16.3, is very fast and better performance, maybe you can upgrade redux to this. great work

**Comment by bertho-zero** [comment]
I'm using the new context API except for redux and react-router, which they use the old API.

(commit: https://github.com/bertho-zero/react-redux-universal-hot-example/commit/ad7d8c771afe2667fc51dc24fb947338b0c4bb7a)

**Comment by bertho-zero** [comment]
I canceled the commit, when I use the Provider of the new context I have a warning:

`Server-side React render was discarded`

**Comment by joacub** [comment]
But not is for the context maybe is the hot loader or dev tools I I’ve every time this

**Comment by joacub** [comment]
Ooo I can se you change more code good catch

**Comment by joacub** [comment]
And in other zone you have a very big error in rest client when the cookie is clean the socket have a error when connect in server side you need pass if the cookie is empty a empty string this work for me

**Comment by joacub** [comment]
i dont understand the last messsage the code is still same-...

**Comment by bertho-zero** [comment]
I do not have push yet.

**Comment by joacub** [comment]
Apparently is good your core sir, I think the problem is in other area not in the context not have sense, and the problem only is warning the server side not match with client ... this is usually not?

**Comment by joacub** [comment]
you dont implement this ?

**Comment by joacub** [comment]
@bertho-zero hi, the problem is in the order in the components, now react count the providers context  in the elements index and when check is a root the first div not match, if the first div container is in teh server and client files the problem is solved.

example 

```
ReactDOM.hydrate(
        <HotEnabler>
          <div style={{ overflowX: 'hidden' }}>
            <Provider store={store} {...providers}>
              <ConnectedRouter history={history}>
                <ReduxAsyncConnect
                  routes={_routes}
                  store={store}
                  helpers={providers}
                >
                  {renderRoutes(_routes)}
                </ReduxAsyncConnect>
              </ConnectedRouter>
            </Provider>
          </div>
        </HotEnabler>,
        dest
      );
```
