### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#409]
You need las headers to axis and socket

**Comment by bertho-zero** [comment]
Headers and accessToken are set in https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/app.js.

**Comment by joacub** [comment]
When, I put headers in my core becouse not is present in socket request and rest rrquest

**Comment by joacub** [comment]
Yes I say this in your core only put Cookie and authorization 
But client up and other headers not is present and is very important becouse in the api don’t see if you don’t psss here

And cookies can be better with cookies paran in array format is very much easy
