### ISSUE TITLE
[question] whats is better featehrs services or client rest

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#411]
whats is the best mthod for use when retrieve info of server for example post pages and list pages of post toolbars etc, whats is better method feathers services or client ??

**Comment by bertho-zero** [comment]
The client (feathers) in front will get his information on services on back (feathers).

But these services are also usable with any rest client (axios, superagent, ...), I advise to use the feathers client as much as possible for simplicity.

**Comment by joacub** [comment]
You are refere feather client to app.service(my service) or to client.get,post,push

**Comment by bertho-zero** [comment]
`app.service(path)` (https://docs.feathersjs.com/api/client.html)
