### ISSUE TITLE
Service worker blank page

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#412]
Service worker load always and load index.html generate when are online... this is very poor any solution ??

**Comment by bertho-zero** [comment]
I'm sorry but I did not understand the problem or the question.

**Comment by bertho-zero** [comment]
This is the normal operation of the service-worker, once installed it is better to load the page only once in the client from a server empty rendering than having to make a request to the server to have a html on which one will apply our javascript client.

It's faster, there is no unnecessary query to the server and the final rendering is the same.
