### ISSUE TITLE
lodash huge files

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#413]
is needed load complete this library, i dont understand what happend with this line 
store.inject = _.partial(inject, store, _, persistConfig); this is neded ? no can use only the one function ?

**Comment by joacub** [comment]
i search and i find this solution,
```js
import partial from 'lodash/partial';
const ph = partial.placeholder;
const inject = partial(fn, ph, fn2);
```
i dont sure is this working same to the old format, i dont ffamiliarize with lodash

**Comment by bertho-zero** [comment]
```js
store.inject = _.partial(inject, store, _, persistConfig);
```
has been replaced by something like that
```js
store.inject = reducers => inject(store, reducers, persistConfig);
```
