### ISSUE TITLE
consider split somethings 

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#414]
in webpack 4 can split more the code and maybe this is best for split something and separete of the main bundle.

```js
optimization: {
    minimize: true,
    splitChunks: {
      chunks: "async",
      minSize: 30000,
      minChunks: Infinity,
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      automaticNameDelimiter: '~',
      name: true,
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/](@feathers.*|jquery.*|material.*|lodash.*|date-fns.*|react.*|redux.*)/,
          name: "vendor",
          chunks: "initial",
          enforce: true
          // priority: -10
        },
        default: false
      }
    }
  },
```

i dont sure if this split bundle in two files more small main for example 450kb and vendor in other 450kb depend of your aplication. if not implement this lines the code is bundle in one file of 1mb or more bigger whats is best solution i dont sure whats is teh best one file with qmb or two files more small, in htttp2 i think is better i dont sure

what you you think

**Comment by bertho-zero** [comment]
I would think to improve this by updating to webpack 4
