### ISSUE TITLE
Heroku deployment issue

### ISSUE THREAD

**Issue by dakkafex** [bertho-zero/react-redux-universal-hot-example#420]
Trying to deploy a freshly forked project on heroku using the heroku branch nets the following error during the build phase.

https://pastebin.com/KF5096Vy

No additional ENV settings have been set in heroku

**Comment by bertho-zero** [comment]
You need to follow this guide: https://github.com/bertho-zero/react-redux-universal-hot-example#deployment-on-heroku

**Comment by bertho-zero** [comment]
This is due to the missing env variable `NODE_PATH`.

**Comment by dakkafex** [comment]
Ah, you'd figure 3 developers looking at it could figure that out... 😄 

Might i suggest adding a little index at the top of the readme to improve readability?

**Comment by bertho-zero** [comment]
Yes, a PR is welcome.
