### ISSUE TITLE
Styled Components Getting styles after render

### ISSUE THREAD

**Issue by p-rk** [bertho-zero/react-redux-universal-hot-example#422]
Followed the documentation as per styled components for SSR and the styled are getting applied on client after the render of the HTML. Any work around on this.

**Comment by bertho-zero** [comment]
This is normal because the style is extracted with ExtractTextPlugin and is added via a script tag, which renders it after HTML.

To have the style at the same time as the HTML I think that it should not be extracted and added via a style tag.

**Comment by p-rk** [comment]
Thanks, yeah got it. I managed to get it working. You're awesome!
