### ISSUE TITLE
Redux Persist Not Persisting the State From LocalForage

### ISSUE THREAD

**Issue by p-rk** [bertho-zero/react-redux-universal-hot-example#427]
I added my reducer to whitelist in client.js and next triggered an API call and dispatched the action in the reducer and the data is getting updated into indexDB -> localforage and reducer as well. But when i refresh the page the data inside the localForage is not getting synced with the store and after that the localForage data is getting updated with initial state. Any work around with this. I checked my reducer its not mutating any state.

**Comment by bertho-zero** [comment]
Can you show me the `@provideHooks` of this container? it should look like

https://github.com/bertho-zero/react-redux-universal-hot-example/blob/fe63bddcd39053680be4a6bc4f244fc1bc688e90/src/containers/App/App.js#L19-L28

**Comment by p-rk** [comment]
Resolved the issue by replacing the data object in client.js
`const data = { ...window.__data, ...storedData, online };`

Since I need the data whether user online or offline from LocalForage.

**Comment by bertho-zero** [comment]
You had no side effects? Do you think I have to change it for everyone?

**Comment by bertho-zero** [comment]
https://github.com/bertho-zero/react-redux-universal-hot-example/pull/428

**Comment by p-rk** [comment]
No side effects at all. It is working as expected. I guess it is better to sync store with localForage always whether the application is offline or online.

**Comment by bertho-zero** [comment]
When rendering on the server side, at the first display or if we do not have the service-worker, the server data is more important than the store, for authentication, etc. These data are the most "fresh".
If there are data that are only accessible from the store then they are added later.

```js
const data = {
  ...storedData,
  ...window.__data,
  ..._.pick(storedData, [/* data always from store */]),
  online
};
```

Can you try with this line? by adding your key in the whitelist and the _.pick?

**Comment by bertho-zero** [comment]
Closed by https://github.com/bertho-zero/react-redux-universal-hot-example/commit/540989a48bfcd71e008965d2ed993fe3f7711e88
