### ISSUE TITLE
Not hot-reload changes inside components

### ISSUE THREAD

**Issue by waskito** [bertho-zero/react-redux-universal-hot-example#429]
![image](https://user-images.githubusercontent.com/4341116/39712510-7e106eba-524d-11e8-9ffe-4b4270012284.png)

When I change content of `src/components/InfoBar/InfoBar.js` (add a paragraph), nothing is updated. But when I change content in a container, it's hot-reloaded.

Did I miss something before running `npm run dev`?

**Comment by lemonCMS** [comment]
Nope, you did not mis something. You need to eliminate the index.js.

So in App.js 
instead of
`import {InfoBar} from 'components'`

you do this
`import {InfoBar} from 'components/InfoBar/InfoBar'`

The it works

**Comment by waskito** [comment]
It's worked, thanks @lemonCMS !!

**Comment by msimonc** [comment]
Also, won't hot reload without removing the dependency from the index.js.  Thanks @lemonCMS !
