### ISSUE TITLE
Delay render until store is rehydrated

### ISSUE THREAD

**Issue by p-rk** [bertho-zero/react-redux-universal-hot-example#432]
@bertho-zero can we delay the render of the application until the store gets rehydrated?

**Comment by bertho-zero** [comment]
This is the case, there is only the counter of people connected to the chat that changes because your socket is connected after the first rendering.

The store is created with the rehydrated data:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/be73b7321f28c69dc5bfa31975038781f832718b/src/client.js#L63-L76

Do you see something else wrong?

**Comment by p-rk** [comment]
Yes, there is Server and Client Mismatch. 

**Example:** 

I have some data which I store in localForage consider an anonymous user and when the user comes back to the site again I wanted to sync users local state in the browser to the redux store for that we are using redux persist based on his local state some things need to be highlighted in the DOM but there is no server local state so when DOM renders on browser the redux store gets updated and then client gets the changes based on local state and React is giving me Server and Client DOM mismatch.

**Comment by lemonCMS** [comment]
@p-rk  There are four possible solutions or none.

1. Dont use localforge but a cookie store.
2. If it is just a style change, do it directly in the dom through the ref method
3. Disable SSR
4. OR..

I created a new lib especially for this problem. [@wicked_query/redux-persist-component](https://www.npmjs.com/package/@wicked_query/redux-persist-component)

What this does is after the componentDidMount, it calls a action with the localstate. Then in your redux reducer you listen for this action and restore the state. 

If needed i could make a fork with this implemented, i am just low on time.

**Comment by bertho-zero** [comment]
@p-rk Can you try with https://github.com/bertho-zero/react-redux-universal-hot-example/pull/445 ?

**Comment by bertho-zero** [comment]
@p-rk  I have the impression that what you are describing is a problem that can be solved like this: https://github.com/bertho-zero/react-redux-universal-hot-example/blob/338fe6a56dd36427fc1fec14dbc44eb533e34716/src/containers/App/App.js#L21-L30

**Comment by p-rk** [comment]
@bertho-zero sorry for my delay. I was busy since last few days so didn't find to check your comments. But surely will try the cookie one and update here. Thanks

**Comment by p-rk** [comment]
With cookies, this works awesome.
Thanks
