### ISSUE TITLE
add .gitattributes for window users

### ISSUE THREAD

**Issue by hornta** [bertho-zero/react-redux-universal-hot-example#433]
add a .gitattributes to tell git not to check the files out as CRLF.

**Comment by Ory4n** [comment]
how do I do that? I get all those errors after npm install.

Do you have a working version of this boilerplate please! I am new to react and am enjoying learning it.

**Comment by bertho-zero** [comment]
@hornta Can you submit a PR ?

**Comment by bertho-zero** [comment]
It would be more of a `git config` problem:
https://git-scm.com/docs/git-config#git-config-coreeol
https://git-scm.com/docs/git-config#git-config-coresafecrlf
https://git-scm.com/docs/git-config#git-config-coreautocrlf
