### ISSUE TITLE
https endpoint

### ISSUE THREAD

**Issue by Trung1704** [bertho-zero/react-redux-universal-hot-example#437]
I make a request to the https endpoint like: https://domain.com/api/auth/authenticate , but I got the response:
Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
Because the proxy in server cannot make a call API to https endpoint. So can you help me edit the http-proxy or some solutions else?

**Comment by synchu** [comment]
I am sure you may have already checked this, but just in case
https://github.com/nodejitsu/node-http-proxy#using-https
or you can remove the proxy altogether.

**Comment by bertho-zero** [comment]
Synchu's answer should help you.
