### ISSUE TITLE
localforage rather than redux-persist-cookie-storage

### ISSUE THREAD

**Issue by vermotr** [bertho-zero/react-redux-universal-hot-example#441]
Hi!

I don't understand why this repo uses [localforage ](https://github.com/localForage/localForage) rather than [redux-persist-cookie-storage](https://github.com/abersager/redux-persist-cookie-storage/blob/server-support/README.md)?

For a universal application, cookies are more suitable and [redux-persist](https://github.com/rt2zz/redux-persist) recommends their usage for a SSR application.

I just want to understand this choice.

**Comment by bertho-zero** [comment]
The server data is injected via window .__ data. Cookies are limited in size and the interest here is to backup client-side data.

Redux-persist is useful when you are in offline mode and therefore without a server.

**Comment by bertho-zero** [comment]
I do not see exactly the problem you are trying to raise, can you fix that and submit a PR?

**Comment by bertho-zero** [comment]
Is this https://github.com/bertho-zero/react-redux-universal-hot-example/pull/445 right for you ?

**Comment by vermotr** [comment]
Thanks a lot for your answer (I understand better your choice) and for the PR. 

I tested #445, but nothing is stored in cookies.

**Comment by bertho-zero** [comment]
I have this:
![image](https://user-images.githubusercontent.com/8525267/40887265-7175fd92-6746-11e8-9440-8a6796725028.png)

**Comment by vermotr** [comment]
That's right, but if you update your state, the cookie is not updated.

**Comment by bertho-zero** [comment]
I tested too, you have to right-click on the key and refresh. But it's kept up to date for me.

**Comment by vermotr** [comment]
Oh sorry, you are right again. Thank you!

A last question, do you have these warnings:
```log
Warning: App: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.
warning.js:33 Warning: App.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.
```

**Comment by vermotr** [comment]
I missed some updates, so I will check if I have the same dependencies as this repo and I will also check the code.

Thank again for your help!

**Comment by bertho-zero** [comment]
Does the PR solve your problem?

**Comment by vermotr** [comment]
Yes, the PR solves my problem. Thank you ;-)
