### ISSUE TITLE
Feathersjs setHeader error

### ISSUE THREAD

**Issue by ducnvhn** [bertho-zero/react-redux-universal-hot-example#447]
hi @bertho-zero ,
I saw your comment [here](https://github.com/feathersjs/authentication/issues/469) but I really don't understand your implementation in this boilerplate. Could you please explain or do you have any plan to fix this ?

**Comment by bertho-zero** [comment]
This is done with:
- https://github.com/bertho-zero/react-redux-universal-hot-example/blob/338fe6a56dd36427fc1fec14dbc44eb533e34716/src/client.js#L63
- https://github.com/bertho-zero/react-redux-universal-hot-example/blob/338fe6a56dd36427fc1fec14dbc44eb533e34716/src/app.js#L29
- https://github.com/bertho-zero/react-redux-universal-hot-example/blob/338fe6a56dd36427fc1fec14dbc44eb533e34716/src/helpers/apiClient.js#L11-L13
