### ISSUE TITLE
Client user is null after refresh

### ISSUE THREAD

**Issue by colinduwe** [bertho-zero/react-redux-universal-hot-example#449]
I'm getting the same behavior as issue #251
I log in and then reload the page. 
props.user and state.user are both null in getDerivedStateFromProps
Oddly, if I go to the Chat page it says "Anonymous" but when I submit a message it is logged with the email.

**Comment by bertho-zero** [comment]
I have not been able to reproduce this bug.

**Comment by bertho-zero** [comment]
@colinduwe Is it fixed?

**Comment by colinduwe** [comment]
Shoot. I meant to close this. I think I was being a doofus.
