### ISSUE TITLE
Docker error building

### ISSUE THREAD

**Issue by BaptisteGarcin** [bertho-zero/react-redux-universal-hot-example#450]
Step 5/14 : RUN set -x ;   addgroup -g $uid -S $user ;   adduser -u $uid -D -S -G $user $user   && exit 0 ; exit 1
 ---> Running in 43d1825d192a
+ addgroup -g 1000 -S root
addgroup: group 'root' in use
+ adduser -u 1000 -D -S -G root root
adduser: user 'root' in use
+ exit 1
ERROR: Service 'app' failed to build: The command '/bin/sh -c set -x ;   addgroup -g $uid -S $user ;   adduser -u $uid -D -S -G $user $user   && exit 0 ; exit 1' returned a non-zero code: 1

**Comment by BaptisteGarcin** [comment]
Furthermore, yarn docker-dev doesn't load css 
I think there is some issues with docker in this boilerplate :/

**Comment by bertho-zero** [comment]
Can you try to do a `yarn docker-build` or` yarn docker-build --no-cache` before `yarn docker-dev`?

**Comment by joker63** [comment]
I have the same error. I tryed yarn docker-build and yarn docker-build --no-cache
http://prntscr.com/k7hahg
My OS Windows 10

**Comment by joker63** [comment]
Windows: If in the file you change "user: $ {USER}" to "user: node", then everything works...
