### ISSUE TITLE
webpack 4

### ISSUE THREAD

**Issue by joker63** [bertho-zero/react-redux-universal-hot-example#457]
I'am using you app from april 2017. I have a problem with switching to webpack 4. Not valid css. How you avoided this error?
http://prntscr.com/k2d5yk

my webpack config:
https://gist.github.com/joker63/3abe1b4f229726b9028f635a26ce7c10

**Comment by bertho-zero** [comment]
Would not it be because you only include a file for config scss? https://gist.github.com/joker63/3abe1b4f229726b9028f635a26ce7c10#file-webpack-config-L120

**Comment by joker63** [comment]
a bit higher
`include: [
          path.resolve(__dirname, '../src'),
          path.resolve(__dirname, '../', 'node_modules', 'react-dates'),
        ],
        exclude: [path.resolve(__dirname, '../src/ui/css/drp.scss')],`

**Comment by bertho-zero** [comment]
Webpack 4 works well at home with these only changes: https://github.com/bertho-zero/react-redux-universal-hot-example/commit/b6d3b7210a355f8ef4b0da33e945394f77749cb8
