### ISSUE TITLE
Error with @featherjs

### ISSUE THREAD

**Issue by Trung1704** [bertho-zero/react-redux-universal-hot-example#462]
I clone project and install it but when run command: npm run build
It show an error
ERROR in ./node_modules/@featherjs/commons/lib/utils.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: "compare" is read-only
And some of codes about compare function. I don't know what is wrong with some packages. Anybody please help me resolve this proplem.
I am using Nodejs v8.11.1 and trying to resolve it by replace old @feather version.

**Comment by bala-agentz** [comment]
We are also facing the same issue while doing it in docker build. 
But this is not reproducible in my local machine (Ubuntu 16.04.4 LTS)

**Comment by bertho-zero** [comment]
@Trung1704 @bala-agentz Can you try with these changes? https://github.com/feathersjs/commons/pull/79/files
