### ISSUE TITLE
Keeping basic-api up to date?

### ISSUE THREAD

**Issue by oyeanuj** [bertho-zero/react-redux-universal-hot-example#47]
Hi @bertho-zero! Firstly, thank you. I am very glad that you are continuing to maintain this repo! :)

I am wondering if you are planning to keep the basic-api branch also upto date with the package updates, etc? I noticed that you have updated happypack, babel, react-hot-loader on master, but not on basic-api.

FWIW, I would like to put in a vote in favor of it. Unfortunately, I can't use feathers, passport, etc and therefore your basic-api branch is super helpful. Having that updated as well, might help a bunch of us :)

Thank you!

**Comment by bertho-zero** [comment]
I will not continue to maintain the 'basic-api' branch, the front and back parts will separate easily.

I will not keep the yeoman plugin either.

These 2 parties multiply the working time, and I have almost no time to take care of this repo so it becomes complicated.
