### ISSUE TITLE
inject dinamic states

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#478]
Its normal when inject dynamic reducers the other states called again all before states called for example in your example if you clicked in the button 10 times, after you go for example to chat and the clicked state is fired 10 times again all time when you called inject({ chat: reducer }) for example.

**Comment by bertho-zero** [comment]
I do not understand the problem, is there one?

**Comment by bertho-zero** [comment]
The state is global to the application (with redux).

You can reset the reducers to the page change in a `componentDidMount` or `@provideHooks`.
