### ISSUE TITLE
Development mode doesn't work correctly

### ISSUE THREAD

**Issue by arfianadam** [bertho-zero/react-redux-universal-hot-example#484]
I did a clean install of this repo, and ran `yarn dev` to start development mode.

This is a screenshot of the demo page:
![image](https://user-images.githubusercontent.com/10904377/47079003-aeee9500-d22e-11e8-96bd-93026e24ca5f.png)

And this is a screenshot of the same page on production:
![image](https://user-images.githubusercontent.com/10904377/47079104-dd6c7000-d22e-11e8-8814-eaf90892f113.png)

Any insight on this problem?

EDIT: It's not just about the visual that doesn't work, the functionality also. This apparently happens because there is an error. See comment bellow.

**Comment by arfianadam** [comment]
The problem lies on `src/redux/create.js:52`
```javascript
window.devToolsExtension ? window.devToolsExtension() : DevTools.instrument(),
```
And the console returns
```
Uncaught (in promise) TypeError: DevTools.instrument is not a function
```
I fixed it by installing Chrome's Redux Devtools. However I think this still needs to be addressed.

**Comment by bertho-zero** [comment]
It's propbably due to the require (instead of import), like:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/5fdd9c82ede37a283181b9ca9ef37804b96f56e7/src/redux/create.js#L39-L42

We need to test `<module>.__esModule ? <module>.default : <module>`
