### ISSUE TITLE
core-js in babel runtime

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#488]
is necesarry mark core-js in .babelrc this not is included in import @babel/polyfill

**Comment by bertho-zero** [comment]
https://babeljs.io/docs/en/babel-runtime-corejs2#difference-from-babel-runtime

> his can be used instead of a polyfill **for any non-instance methods**

https://github.com/bertho-zero/react-redux-universal-hot-example/blob/d4ac680386882bd9a254c53fb3f66ddbeb0d1f55/.babelrc#L16-L21

`corejs2` is used here but does not completely replace polyfill, especially for `.includes`
