### ISSUE TITLE
Plans for the repo?

### ISSUE THREAD

**Issue by oyeanuj** [bertho-zero/react-redux-universal-hot-example#5]
Hi @bertho-zero! I am glad you have started your own fork with updated dependencies. I was wondering if you plan to maintain this repo for the forseeable future? 

If yes, there are a quite a few helpful PRs on the repos which we could consider incorporating here.

Thanks again for maintaining this so far!

**Comment by bertho-zero** [comment]
Hi, thanks it's nice

I plan to add [feathersjs](http://feathersjs.com/), I will soon publish a first version.

**Comment by sauravskumar** [comment]
@bertho-zero so will you be maintaining this project from here on...??? that would be very nice...

**Comment by bertho-zero** [comment]
@sauravskumar Yes I will continue to put what seems missing and I remain open to any proposal

**Comment by sauravskumar** [comment]
@bertho-zero thank you

**Comment by bertho-zero** [comment]
I do not know if you saw but I added feathers, all past features are still there, in addition to secure authentication, real-time services, their hooks ...

For further I planned to clean this up and add more complete examples of feathers. If someone an idea of things to do, let him know

**Comment by jahmaiosullivan** [comment]
Hi bertho-zero. Thanks for maintaining this. The original repo seems to be dead and my project that I am working on is based off of it. If you need any help, do let me know.

**Comment by sauravskumar** [comment]
@bertho-zero i haven't checked out featherjs yet... i just wanted to know is it kinda awesome.. or just another js library which will be replaced one month later?

**Comment by Iuriy-Budnikov** [comment]
Hey guys. 
I am also able to help.
Can we crate separate repo?

**Comment by Iuriy-Budnikov** [comment]
I have 4 projects based on this repo.

**Comment by jahmaiosullivan** [comment]
Hey berthzero, can you explain what this featherjs claim to fame is? I started reading the docs and it just seemed like a lot of hand-wavy feathersjs-will-solve-all-your-problems type stuff. Usually I stay very far away from libraries like these. Can you break down it's purpose in a concise way for me?

**Comment by Iuriy-Budnikov** [comment]
> I started reading the docs and it just seemed like a lot of hand-wavy feathersjs-will-solve-all-your-problems type stuff.

+1

**Comment by oyeanuj** [comment]
@bertho-zero also curious if having featherjs would prevent us from using our own server-side APIs? I know we already need node for server-side rendering but it seems with featherjs, this repo would be moving in the direction of having authentication, etc all be done on the node server? Is that accurate?

**Comment by Iuriy-Budnikov** [comment]
guys lets create separate fork/repo without featherjs ?

**Comment by sauravskumar** [comment]
+1

**Comment by jahmaiosullivan** [comment]
+1. I did a fork of erikas repo here: https://github.com/jahmaiosullivan/react-redux-universal-hot-example. My first order of business will be to update all the dependencies which will I will do by tomorrow. Second order of business will be to add additional docs explaining my learnings about the code.

**Comment by bertho-zero** [comment]
Hi everyone, feathers is just an extension of express that simplifies programming oriented aspect, aspects such as authentication, error handling, a mailer, etc. All parts are optional.

It allows to easily create a REST API (real-time or not) and easily connect to the client. In short it is a way to create services with hooks, an event system, filter events ... It allows to quickly implement all database connectors and sockets manager.

There Feathers only if you want to use this API, is fast to remove it, I made a branch with the old API (without feathers or database) for those wishing to easily connect to their or take only the client: https://github.com/bertho-zero/react-redux-universal-hot-example/tree/basic-api

**Comment by jahmaiosullivan** [comment]
Thanks for the explanation bertho-zero and thanks for creating a branch without it.

**Comment by oyeanuj** [comment]
@bertho-zero Are you also planning to upgrade webpack, and node as well? I am personally using `basic-api` branch but would be happy to see any of them upgraded to follow along accordingly.

**Comment by bertho-zero** [comment]
Yes I plan to upgrade webpack if anyone is ready to make a pull request
