### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Asher978** [bertho-zero/react-redux-universal-hot-example#533]
### Simply cloned and build in dev
Getting this error after changing content in any of the components. Basically hot reload is causing this:

> GET http://localhost:3000/ws/?EIO=3&transport=polling&t=MeZzH9V net::ERR_CONNECTION_REFUSED

Any suggestions? Anyone else getting this?

**Comment by goodguy000** [comment]
@Asher978 I think this issue come from websocket, it has a route use('/ws') in server.js and api.js. You should check these files to make sure that websocket works well or maybe remove all them if you don't use websocket

**Comment by Asher978** [comment]
@goodguy000 i will be using websockets.

i see that backend is initializing sockets in `api.js` by:
```javascript
  .configure(socketio({ path: '/ws' }))
```

but i highly doubt this error is related to that since other sockets requests on the client side are working fine. This error only occurs after the app has hot reloaded. Which is a bit odd!

**Comment by Asher978** [comment]
Note the `websockets` calls failing which is right after a hot reload!

<img width="455" alt="Screen Shot 2019-04-15 at 10 52 45 PM" src="https://user-images.githubusercontent.com/24880042/56178760-5e83a480-5fd1-11e9-88a6-a1e1b3aeda28.png">

**Comment by bertho-zero** [comment]
This is the normal behavior, the server restarts and the connection is lost for a short time.
