### ISSUE TITLE
Babel Typecheck plugin is deprecated

### ISSUE THREAD

**Issue by jared-dykstra** [bertho-zero/react-redux-universal-hot-example#54]
[babel-plug-typecheck](https://github.com/codemix/babel-plugin-typecheck) is marked as deprecated by still used by this project.

> This project is now deprecated, we're now focussing on flow-runtime.

**Comment by bertho-zero** [comment]
I have switched from typecheck to [**flow**](https://flowtype.org/) with flow-runtime and [babel-plugin-flow-runtime](https://github.com/codemix/flow-runtime/tree/master/packages/babel-plugin-flow-runtime)

If you add these lines in your code:
```js
const add = (a: number, b: number): number => a + b;
add(3, 4);
add(3, false);
```
It throw:
![image](https://cloud.githubusercontent.com/assets/8525267/22628409/f2a29168-ebd3-11e6-8d87-93ac5e0d89aa.png)
