### ISSUE TITLE
ssr in hosted example is not rendering 

### ISSUE THREAD

**Issue by yanivel** [bertho-zero/react-redux-universal-hot-example#67]
Open developer tools in chrome
Disable javascript
Load up: https://react-hot-example.herokuapp.com/

The page is blank

**Comment by bertho-zero** [comment]
Hi, would not it be because the client is downloaded from the service worker and not from the server?

Try just after removing the service worker, or try Maj+F5 on source tab.
On a browser without Javascript there is normally no service-worker.
