### ISSUE TITLE
bootstrap custom variable not work

### ISSUE THREAD

**Issue by anhdn** [bertho-zero/react-redux-universal-hot-example#78]
Hi,

I want to change bootstrap custom variable `$brand-primary: #FE9900;` on src/theme/variables.scss but it does not change while the bootstrap.overrides.scss work normally.

I used the repo's .bootstraprc and the package i use `"bootstrap-loader": "^2.0.0-beta.19", "bootstrap-sass": "3.3.7"`.

Do you have any experiences with the issue?

Thanks!

**Comment by bertho-zero** [comment]
I fixed this in https://github.com/bertho-zero/react-redux-universal-hot-example/commit/cd3579be5bb50ddbb59ab153ac5e0f5209a87db0
