### ISSUE TITLE
imagemin implementation

### ISSUE THREAD

**Issue by firdausious** [bertho-zero/react-redux-universal-hot-example#8]
How to implement imagemin on webpack build production ?

**Comment by bertho-zero** [comment]
You can use [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader), just add the loader after another.

```
  module: {
    loaders: [
      ...
      { test: webpackIsomorphicToolsPlugin.regular_expression('images'), loader: 'url-loader?limit=10240!image-webpack' }
    ]
  },
  ...
```

and add query params or add a `imageWebpackLoader` key to your webpack config, as indicated in the documentation of the plugin.
